### ISSUE TITLE
LXC imajı Vagrant ile hata üretiyor

### ISSUE THREAD

**Issue by huseyin** [omu/makine#1]
`debian-stable-server` imajının (diğerlerini denemedim) eski sürümlerinde (< 1.17.1) sorun yaşanmamasına rağmen up-to-date sürümünde Vagrant, aşağıdaki hatayla çıkış yapıyor:

```
==> dev: Starting container...
==> dev: Waiting for machine to boot. This may take a few minutes...
There was an error executing lxc-info
```

Debug modundan alınan dump şu şekilde: https://gist.github.com/huseyin/4964c081a403c74fd91f6b5ad18da68c

**Ortam**

- Provider: `LXC`
- LXC version: `3.0.3`
- Vagrant version: `2.2.4`
- Vagrant LXC plugin version: `1.4.3`
- Image: `debian-stable-server`
- Image version: `1.17.1`

**Comment by roktas** [comment]
vagrant destroy -f

**Comment by huseyin** [comment]
@roktas çözmedi hocam. tüm LXC box'larını kaldırdım, tekrar indirdim, çalıştırdım yine hata verdi.

**Comment by huseyin** [comment]
Sorun çözüldü, issue'yu kapatıyorum. Çözüm adımları:

1. LXC sürümünü `3.1.X`e yükselt
2. LXC ayarlarına `apparmor` ayarını ekle

   ```
   # /etc/lxc/default.conf
   lxc.apparmor.profile = generated
   lxc.apparmor.allow_nesting = 1
   ...
   ```
